[build]
  publish = "dist/event-ball/browser"
  command = "ng build"
[[redirects]]
  from = "/eb-get-events-by-organizer/*"
  to = "/eb-get-events-by-organizer/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[functions]
  directory = "src/netlify-functions"
  node_bundler = "esbuild"