[build]
  publish = "dist/event-ball/browser"
  command = "ng build"
[functions]
  directory = "src/netlify-functions"
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
